title: "Chengyu Bites"
description: "Short, conversational episodes exploring Chinese 成语."
url: "https://kohlenberg.github.io"
baseurl: "/chengyudaily"
cover_image: "/assets/img/podcast-logo.png"
logo: "/assets/img/podcast-logo.png"
author: "Tilman"
email: "tkohlenberg@gmail.com"
owner_name: "Tilman"
owner_email: "tkohlenberg@gmail.com"

  


# Build settings (GitHub Pages-compatible)
markdown: kramdown
theme: null

# Exclude build artifacts if any
exclude:
  - build/
  - .venv/
  - .env
  - README_local.md
