name: Build podcast.xml
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pyyaml requests
      - run: python build_feed.py
      - name: Commit feed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add podcast.xml
          git commit -m "Update podcast.xml" || echo "No changes"
          git push
