name: Build & Deploy (Pages + RSS)

on:
  push:
    branches: [ main ]         # run on every push to main
  workflow_dispatch:            # allow manual runs

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps for feed build
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests

      - name: Build podcast feed
        run: |
          python build_feed.py
          echo "Listing feed file:"
          ls -l podcast.xml || true
          test -s podcast.xml || (echo "ERROR: podcast.xml not created"; exit 1)

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
