on:
  push:
    branches: [ main ]
    paths:
      - "_posts/**"
      - "episodes/**"
      - "_layouts/**"
      - "_includes/**"
      - "assets/**"
      - "index.html"
      - "build_feed.py"
      - "_config.yml"
      - ".github/workflows/pages.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install pyyaml requests
      - run: python build_feed.py
      - uses: actions/configure-pages@v4
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
